name: qir-book
channels:
  - conda-forge
  - microsoft
dependencies:
  - matplotlib
  - numpy
  - pip
  - dotnet-sdk>=6.0
  # Required by .NET Interactive.
  - dotnet-aspnetcore>=6.0
  - notebook
  - llvm-tools=13
  - clangxx=13
  - qsharp
  - pip:
    - sphinx-design
    - jupyter-book
    - pyqir
