#!/bin/bash
set -e
export PATH="$PATH:/home/jovyan/.dotnet/tools"
export DOTNET_ROOT="/srv/conda/envs/notebook/lib/dotnet/"

# Persist environment var changes.
cat <<EOF >> /home/jovyan/.bashrc
export PATH="\$PATH:/home/jovyan/.dotnet/tools"
export DOTNET_ROOT="/srv/conda/envs/notebook/lib/dotnet/"
EOF

echo "## Installing PowerShell notebook support. ##"

/srv/conda/envs/notebook/lib/dotnet/dotnet tool install -g PowerShell
/srv/conda/envs/notebook/lib/dotnet/dotnet tool install -g Microsoft.dotnet-interactive
/srv/conda/envs/notebook/lib/dotnet/dotnet interactive jupyter install